server:
  port: 8002
spring:
  redis:
    database: 0 # Redis数据库索引(默认为0)
    host: 192.168.65.110 # Redis服务器地址
    port: 6379 # Redis服务连接端口
    password: 123456 # Redis服务连接密码
    timeout: 1000 # 连接超时时间(毫秒)
    block-when-exhausted: true
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数(使用负值代表无限制)
        max-wait: -1 # 连接池最大阻塞等待时间(使用负值代表无限制)
        max-idle: 10 # 连接池中最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接
